jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: xenial
      addons:
        snaps:
          - hugo
      script:
        - python hello_world.py
